import React from 'react';
import FullProjectSection from '../fullprojectsection';
import ExploreMore from '../exploremore';
import NavBar from '@/app/components/navbar/navbar';

const harbor_data = {
  title: 'Harbor',
  category: 'Full Stack AI-Enhanced Music Discovery Platform',
  skills: [
    'Next.js',
    'React.js',
    'Tailwind',
    'Firebase',
    'Zustand',
    'Shadcnui',
    'NextAuth',
    'OpenAI Api',
    'Spotify Api',
  ],

  image_url: '/image/harbor.png',
  github_link: 'https://github.com/yeahimjt/harbor',
  live_link: '',
  overview: [
    'As someone who frequently is listening to new albums and user curated playlists, I often find my musical taste not being satisfied. Its rare that I find a song I consider a gem within an entire album that was recommended to me.',
    'This sparked an idea about how streamining services recommendation algorithms work; it requires a lot of data to truly get your recommendations to music you fewer times than not will consider a miss.',
    'Resulting from this idea, I started brainstorming an application that could allow its users to effectively describe their taste in music to bypass needing to like/dislike a large amount of songs.',
  ],
  features: [
    'Harbor relies on Firebase for authentication, database for data, and storage for storing images generated by OpenAi Dalle-3.',
    'Upon signing up users are immediately met with tuning their music recommendations through selecting genres that they like, and providing text based context of any form they wish. An example of text based context they can include can be: "I enjoy music whose producers convey a large soundscape throughout the track building upon the story".',
    'Spotify Api is also integrated to allow for the immediate retrieval of corresponding Spotify data for tracks and playlists that are curated for the user so they can choose to sync playlists created from Harbor to their Spotify account for later listening.',
    'The inclusion of Spotifys Api also allows users to generally browse albums or playlists in detail similar to spotify to allow all actions performed on spotify to be done on Harbor.',
  ],
  challenges:
    'A reasonable challenge I was met with was simply storing the users session including their access token for Spotifys Api to allow their experience browsing music to be seamless. Unfortunately Spotify deemed the project as a hobby not allowing public users to access any of its functionality.',
  results:
    'Harbor became an application I personally use daily. Since the project is not accessible to public users I allowed personal friends to have access to generate their own AI-Enhanced playlists that they regularly use',
  last: '/projects/linkfolio',
  next: '/projects/clinkz',
  warning:
    'Due to Spotify classifying my project as a hobby, only manually selected users can access it. If you wish to demo the application please reach out by email.',
};

const page = () => {
  return (
    <>
      <NavBar />
      <main className='mt-[80px] grid grid-cols-6'>
        <FullProjectSection data={harbor_data} />
        <ExploreMore previous={harbor_data.last} next={harbor_data.next} />
      </main>
    </>
  );
};

export default page;
