export const sampler_projects: ProjectList = [
  {
    title: 'Exhibitify',
    category: 'Full Stack Creative Feedback and Showcase Platform',
    skills: [
      'Next.js',
      'React.js',
      'Tailwind',
      'Firebase',
      'Zustand',
      'Shadcnui',
      'Puppeteer',
      'NextAuth',
    ],
    live_link: '',
    github_link: 'https://github.com/yeahimjt/exhibitify',
    redirect_link: '/projects/exhibitify',
    warning: null,
    image_url: '/image/exhibitify.png',
    color: '#C0D6E8',
  },
  {
    title: 'Harbor',
    category: 'Full Stack AI-Enhanced Music Discovery Platform',
    skills: [
      'Next.js',
      'React.js',
      'Tailwind',
      'Firebase',
      'Zustand',
      'Shadcnui',
      'NextAuth',
      'OpenAI Api',
      'Spotify Api',
    ],
    live_link: null,
    github_link: 'https://github.com/yeahimjt/harbor',
    redirect_link: '/projects/harbor',
    warning:
      'Due to Spotify classifying my project as a hobby, only manually selected users can access it. If you wish to demo the application please reach out by email.',
    image_url: '/image/harbor.png',
    color: '#CCE3D5',
  },
  {
    title: 'Clinkz',
    category: 'Full Stack Amazon Price Tracker',
    skills: [
      'Next.js',
      'React.js',
      'Tailwind',
      'Firebase',
      'Zustand',
      'Shadcnui',
      'NextAuth',
    ],
    live_link: 'https://clinkz.vercel.app/',
    github_link: 'https://github.com/yeahimjt/clinkz',
    redirect_link: '/projects/clinkz',
    warning: null,
    image_url: '/image/clinkz.png',
    color: '#D4D0E1',
  },
];
